[extend]
useDefault = true

[[allowlists]]
description = "Public Chrome manifest RSA key: fixes the extension ID; contains no private component"
regexTarget = "secret"
regexes = ['''^MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAo6qkJZZPAKqi5H4aHzL3Ots3RfdAVKSPpeF0aFkJJL/5Q6PIS4zMPC4zF3Bj9t4y/Bj1qpUznfJ5M6n21xU4\+5xI7vdZ9umJ8fsQn33X3WezOgOr4AjQmkpy1L4Mesh5jTityy48s79CbEYoomq5gDQMlt/a9iZe1i6hjh3NJ3NYHuw3Q1HecqqBnImK28JXpf9vy4mP92hUWF\+a7huKmfzFJ3uRsGoy7pXclJBB1yMeNN3h/q5yRYR\+2D3klAyzNwnKbND1T0NoPxAeQR/5abAAYtpsDXU1MqXt8HigRlVR0blSdgH3ELzHRADcgm2cGDPZRt65X2IKCRZI9hY55QIDAQAB$''']
