[extend]
useDefault = true

[[allowlists]]
description = "Public Chrome manifest RSA key: fixes the extension ID; contains no private component"
regexTarget = "secret"
regexes = ['''^MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvVLErgpNUUY1UO\/Y5QTt\+L8dLhNDTimzTwvJUIcUa2KJCnmt8jsM9OutpZYV5ad\+v31K90eBta6POtjFzVkiD2wHgVdibOhb85m6\+22EAqLU5yEpeK4mw4gJp\+JrKYC1PRHwI5DNIs1a1w3QTy0AgNTHoBmKVVI0XVH86cMysBoEZWp5cdpmSv3QVJVI3QuLBcayhnxHNW\+k\/R1S4TXs\+Y4sE\/2uWInkuppWPM73NLT9v7lnYxNOR6XUG2bLnlE3izP8z2nD5f7jFPZONq\+V3zM9qFr9DCv2X7ET4B8\+YULGHp\/cvTS8xRNunU5iDUeGASMTXvNkrMU0V9BiVXI4BQIDAQAB$''']
