#!/usr/bin/env python3
"""Regenerate/check offline signing fixtures using the pinned official SDK.

The private key below is an intentionally public upstream test key. NEVER FUND
IT. This program accepts no key argument, loads no configuration, and blocks
network connections. Install the pinned SDK in a disposable environment first;
see internal/hyperliquid/testdata/README.md.
"""

import argparse
import copy
import hashlib
import importlib.metadata
import json
from pathlib import Path
import sys


def forbid_network(event, _args):
    if event in {"socket.connect", "socket.connect_ex", "socket.getaddrinfo"}:
        raise RuntimeError("network access is prohibited while generating fixtures")


sys.addaudithook(forbid_network)

from eth_account import Account
from eth_utils import keccak
import msgpack
from hyperliquid.utils import signing as sdk
from hyperliquid.utils import types as sdk_types


SDK_COMMIT = "2fdb18f9517675ea03695a0962bd19eece9c83f0"
SDK_REPOSITORY = "https://github.com/hyperliquid-dex/hyperliquid-python-sdk"
SDK_ARCHIVE_SHA256 = "e48dff272dbb1a021177d0a7e3f0be092665f060ec6a6b3224c3f51b47c43896"
SOURCE_SHA256 = {
    "hyperliquid/utils/signing.py": "938ec0a1f9611874b423ca946696e19a71d32d14709f521ea5d526f4398c0b85",
    "hyperliquid/utils/types.py": "5161dfcfc5ea39f1540d4e68ffd79520b9f5ab7aff9ce88a8440d6e6dabb88ba",
}
PACKAGE_VERSIONS = {
    "hyperliquid-python-sdk": "0.24.0",
    "eth-account": "0.13.7",
    "eth-utils": "5.3.1",
    "msgpack": "1.1.1",
}
# Public test key from upstream tests/signing_test.py. It is not a credential.
TEST_PRIVATE_KEY = "0x0123456789012345678901234567890123456789012345678901234567890123"
NONCE = 1700000000123
EXPIRY = NONCE + 60000
DESTINATION = "0x1111111111111111111111111111111111111111"
BUILDER = "0x2222222222222222222222222222222222222222"
VAULT = "0x3333333333333333333333333333333333333333"
VALIDATOR = "0x4444444444444444444444444444444444444444"
AGENT = "0x5555555555555555555555555555555555555555"
CLOID = "0x" + "0" * 28 + "01ab"
TOKEN = "USDC:0x6d1e7cde53ba9467b783cb7c530ce054"
FIXTURE_PATH = Path(__file__).resolve().parent.parent / "internal/hyperliquid/testdata/official-sdk-vectors.json"


class RecordingWallet:
    """Record the exact SignableMessage passed by the upstream signing code."""

    def __init__(self):
        self.wallet = Account.from_key(TEST_PRIVATE_KEY)
        self.message = None
        self.signed_message = None

    @property
    def address(self):
        return self.wallet.address

    def sign_message(self, message):
        self.message = message
        self.signed_message = self.wallet.sign_message(message)
        return self.signed_message

    def digest(self, signature):
        # EIP-191 framing of the message generated by the SDK's encode_typed_data.
        value = keccak(b"\x19" + self.message.version + self.message.header + self.message.body)
        assert value == self.signed_message.message_hash
        recovered = Account.recover_message(
            self.message, vrs=(signature["v"], signature["r"], signature["s"])
        )
        assert recovered == self.address
        return "0x" + value.hex()


def wire_order(*, trigger=False, cloid=False):
    order = {
        "coin": "fixture",
        "is_buy": not trigger,
        "sz": 1.25,
        "limit_px": 2500.125,
        "reduce_only": trigger,
        "order_type": (
            {"trigger": {"triggerPx": 2400.5, "isMarket": True, "tpsl": "sl"}}
            if trigger else {"limit": {"tif": "Gtc"}}
        ),
    }
    if cloid:
        order["cloid"] = sdk_types.Cloid.from_str(CLOID)
    return sdk.order_request_to_order_wire(order, 4)


def l1_actions():
    # Ordinary dictionaries intentionally preserve the official SDK's insertion
    # order. Never sort keys before MessagePack encoding.
    limit = wire_order()
    trigger = wire_order(trigger=True)
    return [
        ("order-limit", sdk.order_wires_to_order_action([limit])),
        ("order-trigger", sdk.order_wires_to_order_action([trigger])),
        ("order-builder-cloid-normalTpsl", sdk.order_wires_to_order_action(
            [wire_order(cloid=True), trigger], {"b": BUILDER, "f": 10}, "normalTpsl"
        )),
        ("order-positionTpsl", sdk.order_wires_to_order_action([trigger], grouping="positionTpsl")),
        ("cancel", {"type": "cancel", "cancels": [{"a": 4, "o": 123456789}, {"a": 1, "o": 987654321}]}),
        ("cancelByCloid", {"type": "cancelByCloid", "cancels": [{"asset": 4, "cloid": CLOID}]}),
        # The SDK exposes batchModify; the single modify and TWAP wire shapes
        # below are documented by the official exchange-endpoint API reference.
        ("modify", {"type": "modify", "oid": 123456789, "order": limit}),
        ("modify-cloid", {"type": "modify", "oid": CLOID, "order": wire_order(cloid=True)}),
        ("batchModify", {"type": "batchModify", "modifies": [
            {"oid": 123456789, "order": limit}, {"oid": CLOID, "order": wire_order(cloid=True)}
        ]}),
        ("updateLeverage-cross", {"type": "updateLeverage", "asset": 4, "isCross": True, "leverage": 5}),
        ("updateLeverage-isolated", {"type": "updateLeverage", "asset": 4, "isCross": False, "leverage": 3}),
        ("updateIsolatedMargin-add", {"type": "updateIsolatedMargin", "asset": 4, "isBuy": True, "ntli": 12500000}),
        ("updateIsolatedMargin-remove", {"type": "updateIsolatedMargin", "asset": 4, "isBuy": True, "ntli": -12500000}),
        ("scheduleCancel-set", {"type": "scheduleCancel", "time": NONCE + 30000}),
        ("scheduleCancel-clear", {"type": "scheduleCancel"}),
        ("twapOrder", {"type": "twapOrder", "twap": {"a": 4, "b": True, "s": "1.25", "r": False, "m": 5, "t": True}}),
        ("twapCancel", {"type": "twapCancel", "a": 4, "t": 123456789}),
        ("noop", {"type": "noop"}),
    ]


def user_actions(signer_address):
    # All action metadata is supplied before signing. The SDK repeats assignment
    # of the same chain fields; generation asserts it did not change the input.
    return [
        ("usdSend", {"destination": DESTINATION, "amount": "1.25", "time": NONCE, "type": "usdSend"}, sdk.sign_usd_transfer_action),
        ("spotSend", {"destination": DESTINATION, "amount": "1.25", "token": TOKEN, "time": NONCE, "type": "spotSend"}, sdk.sign_spot_transfer_action),
        ("withdraw3", {"destination": DESTINATION, "amount": "1.25", "time": NONCE, "type": "withdraw3"}, sdk.sign_withdraw_from_bridge_action),
        ("usdClassTransfer", {"type": "usdClassTransfer", "amount": "1.25", "toPerp": True, "nonce": NONCE}, sdk.sign_usd_class_transfer_action),
        ("sendAsset", {"type": "sendAsset", "destination": DESTINATION, "sourceDex": "", "destinationDex": "spot", "token": TOKEN, "amount": "1.25", "fromSubAccount": "", "nonce": NONCE}, sdk.sign_send_asset_action),
        ("approveAgent", {"type": "approveAgent", "agentAddress": AGENT, "agentName": "fixture-agent", "nonce": NONCE}, sdk.sign_agent),
        ("approveBuilderFee", {"maxFeeRate": "0.01%", "builder": BUILDER, "nonce": NONCE, "type": "approveBuilderFee"}, sdk.sign_approve_builder_fee),
        ("tokenDelegate", {"validator": VALIDATOR, "wei": 1250000000, "isUndelegate": False, "nonce": NONCE, "type": "tokenDelegate"}, sdk.sign_token_delegate_action),
        ("userDexAbstraction", {"type": "userDexAbstraction", "user": signer_address.lower(), "enabled": True, "nonce": NONCE}, sdk.sign_user_dex_abstraction_action),
        ("userSetAbstraction", {"type": "userSetAbstraction", "user": signer_address.lower(), "abstraction": "unifiedAccount", "nonce": NONCE}, sdk.sign_user_set_abstraction_action),
    ]


def check_sdk():
    for name, expected in PACKAGE_VERSIONS.items():
        actual = importlib.metadata.version(name)
        if actual != expected:
            raise RuntimeError(f"{name}: expected {expected}, found {actual}")
    for path, module in (("hyperliquid/utils/signing.py", sdk), ("hyperliquid/utils/types.py", sdk_types)):
        actual = hashlib.sha256(Path(module.__file__).read_bytes()).hexdigest()
        if actual != SOURCE_SHA256[path]:
            raise RuntimeError(f"{path} differs from pinned official SDK commit {SDK_COMMIT}")


def generate():
    check_sdk()
    wallet = RecordingWallet()
    vectors = []
    for network in ("mainnet", "testnet"):
        mainnet = network == "mainnet"
        for name, action in l1_actions():
            for vault in (None, VAULT):
                for expiry in (None, EXPIRY):
                    request = {"action": copy.deepcopy(action), "nonce": NONCE}
                    if vault is not None:
                        request["vaultAddress"] = vault
                    if expiry is not None:
                        request["expiresAfter"] = expiry
                    signature = sdk.sign_l1_action(wallet, request["action"], vault, NONCE, expiry, mainnet)
                    vector = {
                        "name": f"{network}/{name}/{'vault' if vault else 'no-vault'}/{'expiry' if expiry else 'no-expiry'}",
                        "scheme": "l1", "network": network, "signerAddress": wallet.address,
                        "input": request, "digest": wallet.digest(signature),
                        "actionHash": "0x" + sdk.action_hash(action, vault, NONCE, expiry).hex(),
                        "msgpack": "0x" + msgpack.packb(action).hex(),
                        "signature": signature,
                    }
                    vectors.append(vector)
        for name, original, signer in user_actions(wallet.address):
            action = copy.deepcopy(original)
            action["signatureChainId"] = "0x66eee"
            action["hyperliquidChain"] = "Mainnet" if mainnet else "Testnet"
            before = copy.deepcopy(action)
            signature = signer(wallet, action, mainnet)
            assert action == before
            vectors.append({
                "name": f"{network}/{name}", "scheme": "user", "network": network,
                "signerAddress": wallet.address, "input": {"action": action, "nonce": NONCE},
                "digest": wallet.digest(signature), "signature": signature,
            })
    return {
        "schemaVersion": 1,
        "warning": "OFFLINE TEST FIXTURES ONLY. The public upstream test key must never hold assets. All timestamps are intentionally expired. No request was submitted to an exchange.",
        "sdk": {
            "repository": SDK_REPOSITORY, "commit": SDK_COMMIT, "version": PACKAGE_VERSIONS["hyperliquid-python-sdk"],
            "archiveSha256": SDK_ARCHIVE_SHA256, "sourceSha256": SOURCE_SHA256,
            "license": "MIT", "licenseFile": "hyperliquid-sdk-LICENSE.txt",
            "packages": PACKAGE_VERSIONS,
        },
        "testPrivateKey": TEST_PRIVATE_KEY,
        "signerAddress": wallet.address,
        "vectors": vectors,
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="replace only the checked-in offline fixture JSON")
    args = parser.parse_args()
    result = generate()
    encoded = json.dumps(result, indent=2, ensure_ascii=True) + "\n"
    if args.write:
        FIXTURE_PATH.parent.mkdir(parents=True, exist_ok=True)
        FIXTURE_PATH.write_text(encoded, encoding="utf-8")
        print(f"Wrote {len(result['vectors'])} offline official-SDK vectors")
    elif not FIXTURE_PATH.exists() or FIXTURE_PATH.read_text(encoding="utf-8") != encoded:
        raise SystemExit("Fixture mismatch; inspect the pinned SDK and regenerate with --write")
    else:
        print(f"Verified {len(result['vectors'])} offline official-SDK vectors")


if __name__ == "__main__":
    main()
